$("#addClient").click(function()
    {
      $("#content_fact").load("../client/newClient");
      $("#editClient").removeClass("active");
      $("#searchClient").removeClass("active");
      $("#deleteClient").removeClass("active");
      $("#addClient").addClass("active");
      $("#editRoute").removeClass("active");
      $("#searchRoute").removeClass("active");
      $("#addRoute").removeClass("active");
      $("#deleteRoute").removeClass("active");
      $("#editViaje").removeClass("active");
      $("#searchViaje").removeClass("active");
      $("#addViaje").removeClass("active");
      $("#deleteViaje").removeClass("active");
      
   });
$("#editClient").click(function()
    {
      $("#content_fact").load("../client/editClient");
      $("#addClient").removeClass("active");
      $("#searchClient").removeClass("active");
      $("#deleteClient").removeClass("active");
      $("#editClient").addClass("active");
      $("#editRoute").removeClass("active");
      $("#searchRoute").removeClass("active");
      $("#addRoute").removeClass("active");
      $("#deleteRoute").removeClass("active");
      $("#editViaje").removeClass("active");
      $("#searchViaje").removeClass("active");
      $("#addViaje").removeClass("active");
      $("#deleteViaje").removeClass("active");

   });
$("#deleteClient").click(function()
    {
      $("#content_fact").load("../client/deleteClient");
      $("#editClient").removeClass("active");
      $("#searchClient").removeClass("active");
      $("#addClient").removeClass("active");
      $("#deleteClient").addClass("active");
      $("#editRoute").removeClass("active");
      $("#searchRoute").removeClass("active");
      $("#addRoute").removeClass("active");
      $("#deleteRoute").removeClass("active");
      $("#editViaje").removeClass("active");
      $("#searchViaje").removeClass("active");
      $("#addViaje").removeClass("active");
      $("#deleteViaje").removeClass("active");

   });
$("#searchClient").click(function()
    {
      $("#content_fact").load("../client/searchClient");
      $("#editClient").removeClass("active");
      $("#addClient").removeClass("active");
      $("#deleteClient").removeClass("active");
      $("#searchClient").addClass("active");
      $("#editRoute").removeClass("active");
      $("#searchRoute").removeClass("active");
      $("#addRoute").removeClass("active");
      $("#deleteRoute").removeClass("active");
      $("#editViaje").removeClass("active");
      $("#searchViaje").removeClass("active");
      $("#addViaje").removeClass("active");
      $("#deleteViaje").removeClass("active");

   });

$("#addRoute").click(function()
    {
      $("#content_fact").load("../route/newRoute");
      $("#editRoute").removeClass("active");
      $("#searchRoute").removeClass("active");
      $("#deleteRoute").removeClass("active");
      $("#addRoute").addClass("active");
      $("#editClient").removeClass("active");
      $("#addClient").removeClass("active");
      $("#deleteClient").removeClass("active");
      $("#searchClient").removeClass("active");
      $("#editViaje").removeClass("active");
      $("#searchViaje").removeClass("active");
      $("#addViaje").removeClass("active");
      $("#deleteViaje").removeClass("active");
   });
$("#editRoute").click(function()
    {
      $("#content_fact").load("../route/editRoute");
      $("#addRoute").removeClass("active");
      $("#searchRoute").removeClass("active");
      $("#deleteRoute").removeClass("active");
      $("#editRoute").addClass("active");
      $("#editClient").removeClass("active");
      $("#addClient").removeClass("active");
      $("#deleteClient").removeClass("active");
      $("#searchClient").removeClass("active");
      $("#editViaje").removeClass("active");
      $("#searchViaje").removeClass("active");
      $("#addViaje").removeClass("active");
      $("#deleteViaje").removeClass("active");
   });
$("#deleteRoute").click(function()
    {
      $("#content_fact").load("../route/deleteRoute");
      $("#editRoute").removeClass("active");
      $("#searchRoute").removeClass("active");
      $("#addRoute").removeClass("active");
      $("#deleteRoute").addClass("active");
      $("#editClient").removeClass("active");
      $("#addClient").removeClass("active");
      $("#deleteClient").removeClass("active");
      $("#searchClient").removeClass("active");
      $("#editViaje").removeClass("active");
      $("#searchViaje").removeClass("active");
      $("#addViaje").removeClass("active");
      $("#deleteViaje").removeClass("active");
   });
$("#searchRoute").click(function()
    {
      $("#content_fact").load("../route/searchRoute");
      $("#editRoute").removeClass("active");
      $("#addRoute").removeClass("active");
      $("#deleteRoute").removeClass("active");
      $("#searchRoute").addClass("active");
      $("#editClient").removeClass("active");
      $("#addClient").removeClass("active");
      $("#deleteClient").removeClass("active");
      $("#searchClient").removeClass("active");
      $("#editViaje").removeClass("active");
      $("#searchViaje").removeClass("active");
      $("#addViaje").removeClass("active");
      $("#deleteViaje").removeClass("active");
   });


$("#addViaje").click(function()
    {
      $("#content_fact").load("../viaje/newViaje");
      $("#editViaje").removeClass("active");
      $("#searchViaje").removeClass("active");
      $("#deleteViaje").removeClass("active");
      $("#addViaje").addClass("active");
      $("#editClient").removeClass("active");
      $("#addClient").removeClass("active");
      $("#deleteClient").removeClass("active");
      $("#searchClient").removeClass("active");
      $("#editRoute").removeClass("active");
      $("#searchRoute").removeClass("active");
      $("#addRoute").removeClass("active");
      $("#deleteRoute").removeClass("active");
   });
$("#editViaje").click(function()
    {
      $("#content_fact").load("../viaje/editViaje");
      $("#addViaje").removeClass("active");
      $("#searchViaje").removeClass("active");
      $("#deleteViaje").removeClass("active");
      $("#editViaje").addClass("active");
      $("#editClient").removeClass("active");
      $("#addClient").removeClass("active");
      $("#deleteClient").removeClass("active");
      $("#searchClient").removeClass("active");
      $("#editRoute").removeClass("active");
      $("#searchRoute").removeClass("active");
      $("#addRoute").removeClass("active");
      $("#deleteRoute").removeClass("active");
   });
$("#deleteViaje").click(function()
    {
      $("#content_fact").load("../viaje/deleteViaje");
      $("#editViaje").removeClass("active");
      $("#searchViaje").removeClass("active");
      $("#addViaje").removeClass("active");
      $("#deleteViaje").addClass("active");
      $("#editClient").removeClass("active");
      $("#addClient").removeClass("active");
      $("#deleteClient").removeClass("active");
      $("#searchClient").removeClass("active");
      $("#editRoute").removeClass("active");
      $("#searchRoute").removeClass("active");
      $("#addRoute").removeClass("active");
      $("#deleteRoute").removeClass("active");
   });
$("#searchViaje").click(function()
    {
      $("#content_fact").load("../viaje/searchViaje");
      $("#editViaje").removeClass("active");
      $("#addViaje").removeClass("active");
      $("#deleteViaje").removeClass("active");
      $("#searchViaje").addClass("active");
      $("#editClient").removeClass("active");
      $("#addClient").removeClass("active");
      $("#deleteClient").removeClass("active");
      $("#searchClient").removeClass("active");
      $("#editRoute").removeClass("active");
      $("#searchRoute").removeClass("active");
      $("#addRoute").removeClass("active");
      $("#deleteRoute").removeClass("active");
   });

