$("#addUnit").click(function()
    {
      $("#content_flotas").load("unit/newUnit");
      $("#editUnit").removeClass("active");
      $("#searchUnit").removeClass("active");
      $("#deleteUnit").removeClass("active");
      $("#addUnit").addClass("active");
      $("#editChofer").removeClass("active");
      $("#searchChofer").removeClass("active");
      $("#addChofer").removeClass("active");
      $("#deleteChofer").removeClass("active");
      $("#editChasis").removeClass("active");
      $("#searchChasis").removeClass("active");
      $("#addChasis").removeClass("active");
      $("#deleteChasis").removeClass("active");
      $("#editContenedor").removeClass("active");
      $("#searchContenedor").removeClass("active");
      $("#addContenedor").removeClass("active");
      $("#deleteContenedor").removeClass("active");
      $("#editCabezal").removeClass("active");
      $("#searchCabezal").removeClass("active");
      $("#addCabezal").removeClass("active");
      $("#deleteCabezal").removeClass("active");
   });
$("#editUnit").click(function()
    {
      $("#content_flotas").load("unit/editUnit");
      $("#addUnit").removeClass("active");
      $("#searchUnit").removeClass("active");
      $("#deleteUnit").removeClass("active");
      $("#editUnit").addClass("active");
      $("#editChofer").removeClass("active");
      $("#searchChofer").removeClass("active");
      $("#addChofer").removeClass("active");
      $("#deleteChofer").removeClass("active");
      $("#editChasis").removeClass("active");
      $("#searchChasis").removeClass("active");
      $("#addChasis").removeClass("active");
      $("#deleteChasis").removeClass("active");
      $("#editContenedor").removeClass("active");
      $("#searchContenedor").removeClass("active");
      $("#addContenedor").removeClass("active");
      $("#deleteContenedor").removeClass("active");
      $("#editCabezal").removeClass("active");
      $("#searchCabezal").removeClass("active");
      $("#addCabezal").removeClass("active");
      $("#deleteCabezal").removeClass("active");
   });
$("#deleteUnit").click(function()
    {
      $("#content_flotas").load("unit/deleteUnit");
      $("#editUnit").removeClass("active");
      $("#searchUnit").removeClass("active");
      $("#addUnit").removeClass("active");
      $("#deleteUnit").addClass("active");
      $("#editChofer").removeClass("active");
      $("#searchChofer").removeClass("active");
      $("#addChofer").removeClass("active");
      $("#deleteChofer").removeClass("active");
      $("#editChasis").removeClass("active");
      $("#searchChasis").removeClass("active");
      $("#addChasis").removeClass("active");
      $("#deleteChasis").removeClass("active");
      $("#editContenedor").removeClass("active");
      $("#searchContenedor").removeClass("active");
      $("#addContenedor").removeClass("active");
      $("#deleteContenedor").removeClass("active");
      $("#editCabezal").removeClass("active");
      $("#searchCabezal").removeClass("active");
      $("#addCabezal").removeClass("active");
      $("#deleteCabezal").removeClass("active");
   });
$("#searchUnit").click(function()
    {
      $("#content_flotas").load("unit/searchUnit");
      $("#editUnit").removeClass("active");
      $("#addUnit").removeClass("active");
      $("#deleteUnit").removeClass("active");
      $("#searchUnit").addClass("active");
      $("#editChofer").removeClass("active");
      $("#searchChofer").removeClass("active");
      $("#addChofer").removeClass("active");
      $("#deleteChofer").removeClass("active");
      $("#editChasis").removeClass("active");
      $("#searchChasis").removeClass("active");
      $("#addChasis").removeClass("active");
      $("#deleteChasis").removeClass("active");
      $("#editContenedor").removeClass("active");
      $("#searchContenedor").removeClass("active");
      $("#addContenedor").removeClass("active");
      $("#deleteContenedor").removeClass("active");
      $("#editCabezal").removeClass("active");
      $("#searchCabezal").removeClass("active");
      $("#addCabezal").removeClass("active");
      $("#deleteCabezal").removeClass("active");
   });


$("#addChofer").click(function()
    {
      $("#content_flotas").load("chofer/newChofer");
      $("#editChofer").removeClass("active");
      $("#searchChofer").removeClass("active");
      $("#deleteChofer").removeClass("active");
      $("#addChofer").addClass("active");
      $("#editUnit").removeClass("active");
      $("#addUnit").removeClass("active");
      $("#deleteUnit").removeClass("active");
      $("#searchUnit").removeClass("active");
      $("#editChasis").removeClass("active");
      $("#searchChasis").removeClass("active");
      $("#addChasis").removeClass("active");
      $("#deleteChasis").removeClass("active");
      $("#editContenedor").removeClass("active");
      $("#searchContenedor").removeClass("active");
      $("#addContenedor").removeClass("active");
      $("#deleteContenedor").removeClass("active");
      $("#editCabezal").removeClass("active");
      $("#searchCabezal").removeClass("active");
      $("#addCabezal").removeClass("active");
      $("#deleteCabezal").removeClass("active");
   });
$("#editChofer").click(function()
    {
      $("#content_flotas").load("chofer/editChofer");
      $("#addChofer").removeClass("active");
      $("#searchChofer").removeClass("active");
      $("#deleteChofer").removeClass("active");
      $("#editChofer").addClass("active");
      $("#editUnit").removeClass("active");
      $("#addUnit").removeClass("active");
      $("#deleteUnit").removeClass("active");
      $("#searchUnit").removeClass("active");
      $("#editChasis").removeClass("active");
      $("#searchChasis").removeClass("active");
      $("#addChasis").removeClass("active");
      $("#deleteChasis").removeClass("active");
      $("#editContenedor").removeClass("active");
      $("#searchContenedor").removeClass("active");
      $("#addContenedor").removeClass("active");
      $("#deleteContenedor").removeClass("active");
      $("#editCabezal").removeClass("active");
      $("#searchCabezal").removeClass("active");
      $("#addCabezal").removeClass("active");
      $("#deleteCabezal").removeClass("active");
   });
$("#deleteChofer").click(function()
    {
      $("#content_flotas").load("chofer/deleteChofer");
      $("#editChofer").removeClass("active");
      $("#searchChofer").removeClass("active");
      $("#addChofer").removeClass("active");
      $("#deleteChofer").addClass("active");
      $("#editUnit").removeClass("active");
      $("#addUnit").removeClass("active");
      $("#deleteUnit").removeClass("active");
      $("#searchUnit").removeClass("active");
      $("#editChasis").removeClass("active");
      $("#searchChasis").removeClass("active");
      $("#addChasis").removeClass("active");
      $("#deleteChasis").removeClass("active");
      $("#editContenedor").removeClass("active");
      $("#searchContenedor").removeClass("active");
      $("#addContenedor").removeClass("active");
      $("#deleteContenedor").removeClass("active");
      $("#editCabezal").removeClass("active");
      $("#searchCabezal").removeClass("active");
      $("#addCabezal").removeClass("active");
      $("#deleteCabezal").removeClass("active");
   });
$("#searchChofer").click(function()
    {
      $("#content_flotas").load("chofer/searchChofer");
      $("#editChofer").removeClass("active");
      $("#addChofer").removeClass("active");
      $("#deleteChofer").removeClass("active");
      $("#searchChofer").addClass("active");
      $("#editUnit").removeClass("active");
      $("#addUnit").removeClass("active");
      $("#deleteUnit").removeClass("active");
      $("#searchUnit").removeClass("active");
      $("#editChasis").removeClass("active");
      $("#searchChasis").removeClass("active");
      $("#addChasis").removeClass("active");
      $("#deleteChasis").removeClass("active");
      $("#editContenedor").removeClass("active");
      $("#searchContenedor").removeClass("active");
      $("#addContenedor").removeClass("active");
      $("#deleteContenedor").removeClass("active");
      $("#editCabezal").removeClass("active");
      $("#searchCabezal").removeClass("active");
      $("#addCabezal").removeClass("active");
      $("#deleteCabezal").removeClass("active");
   });


$("#addChasis").click(function()
    {
      $("#content_flotas").load("chasis/newChasis");
      $("#editChasis").removeClass("active");
      $("#searchChasis").removeClass("active");
      $("#deleteChasis").removeClass("active");
      $("#addChasis").addClass("active");
      $("#editUnit").removeClass("active");
      $("#addUnit").removeClass("active");
      $("#deleteUnit").removeClass("active");
      $("#searchUnit").removeClass("active");
      $("#editChofer").removeClass("active");
      $("#searchChofer").removeClass("active");
      $("#addChofer").removeClass("active");
      $("#deleteChofer").removeClass("active");
      $("#editContenedor").removeClass("active");
      $("#searchContenedor").removeClass("active");
      $("#addContenedor").removeClass("active");
      $("#deleteContenedor").removeClass("active");
      $("#editCabezal").removeClass("active");
      $("#searchCabezal").removeClass("active");
      $("#addCabezal").removeClass("active");
      $("#deleteCabezal").removeClass("active");
   });
$("#editChasis").click(function()
    {
      $("#content_flotas").load("chasis/editChasis");
      $("#addChasis").removeClass("active");
      $("#searchChasis").removeClass("active");
      $("#deleteChasis").removeClass("active");
      $("#editChasis").addClass("active");
      $("#editUnit").removeClass("active");
      $("#addUnit").removeClass("active");
      $("#deleteUnit").removeClass("active");
      $("#searchUnit").removeClass("active");
      $("#editChofer").removeClass("active");
      $("#searchChofer").removeClass("active");
      $("#addChofer").removeClass("active");
      $("#deleteChofer").removeClass("active");
      $("#editContenedor").removeClass("active");
      $("#searchContenedor").removeClass("active");
      $("#addContenedor").removeClass("active");
      $("#deleteContenedor").removeClass("active");
      $("#editCabezal").removeClass("active");
      $("#searchCabezal").removeClass("active");
      $("#addCabezal").removeClass("active");
      $("#deleteCabezal").removeClass("active");
   });
$("#deleteChasis").click(function()
    {
      $("#content_flotas").load("chasis/deleteChasis");
      $("#editChasis").removeClass("active");
      $("#searchChasis").removeClass("active");
      $("#addChasis").removeClass("active");
      $("#deleteChasis").addClass("active");
      $("#editUnit").removeClass("active");
      $("#addUnit").removeClass("active");
      $("#deleteUnit").removeClass("active");
      $("#searchUnit").removeClass("active");
      $("#editChofer").removeClass("active");
      $("#searchChofer").removeClass("active");
      $("#addChofer").removeClass("active");
      $("#deleteChofer").removeClass("active");
      $("#editContenedor").removeClass("active");
      $("#searchContenedor").removeClass("active");
      $("#addContenedor").removeClass("active");
      $("#deleteContenedor").removeClass("active");
      $("#editCabezal").removeClass("active");
      $("#searchCabezal").removeClass("active");
      $("#addCabezal").removeClass("active");
      $("#deleteCabezal").removeClass("active");
   });
$("#searchChasis").click(function()
    {
      $("#content_flotas").load("chasis/searchChasis");
      $("#editChasis").removeClass("active");
      $("#addChasis").removeClass("active");
      $("#deleteChasis").removeClass("active");
      $("#searchChasis").addClass("active");
      $("#editUnit").removeClass("active");
      $("#addUnit").removeClass("active");
      $("#deleteUnit").removeClass("active");
      $("#searchUnit").removeClass("active");
      $("#editChofer").removeClass("active");
      $("#searchChofer").removeClass("active");
      $("#addChofer").removeClass("active");
      $("#deleteChofer").removeClass("active");
      $("#editContenedor").removeClass("active");
      $("#searchContenedor").removeClass("active");
      $("#addContenedor").removeClass("active");
      $("#deleteContenedor").removeClass("active");
      $("#editCabezal").removeClass("active");
      $("#searchCabezal").removeClass("active");
      $("#addCabezal").removeClass("active");
      $("#deleteCabezal").removeClass("active");
   });


$("#addContenedor").click(function()
    {
      $("#content_flotas").load("contenedor/newContenedor");
      $("#editContenedor").removeClass("active");
      $("#searchContenedor").removeClass("active");
      $("#deleteContenedor").removeClass("active");
      $("#addContenedor").addClass("active");
      $("#editUnit").removeClass("active");
      $("#addUnit").removeClass("active");
      $("#deleteUnit").removeClass("active");
      $("#searchUnit").removeClass("active");
      $("#editChofer").removeClass("active");
      $("#searchChofer").removeClass("active");
      $("#addChofer").removeClass("active");
      $("#deleteChofer").removeClass("active");
      $("#editChasis").removeClass("active");
      $("#searchChasis").removeClass("active");
      $("#addChasis").removeClass("active");
      $("#deleteChasis").removeClass("active");
      $("#editCabezal").removeClass("active");
      $("#searchCabezal").removeClass("active");
      $("#addCabezal").removeClass("active");
      $("#deleteCabezal").removeClass("active");
   });
$("#editContenedor").click(function()
    {
      $("#content_flotas").load("contenedor/editContenedor");
      $("#addContenedor").removeClass("active");
      $("#searchContenedor").removeClass("active");
      $("#deleteContenedor").removeClass("active");
      $("#editContenedor").addClass("active");
      $("#editUnit").removeClass("active");
      $("#addUnit").removeClass("active");
      $("#deleteUnit").removeClass("active");
      $("#searchUnit").removeClass("active");
      $("#editChofer").removeClass("active");
      $("#searchChofer").removeClass("active");
      $("#addChofer").removeClass("active");
      $("#deleteChofer").removeClass("active");
      $("#editChasis").removeClass("active");
      $("#searchChasis").removeClass("active");
      $("#addChasis").removeClass("active");
      $("#deleteChasis").removeClass("active");
      $("#editCabezal").removeClass("active");
      $("#searchCabezal").removeClass("active");
      $("#addCabezal").removeClass("active");
      $("#deleteCabezal").removeClass("active");
   });
$("#deleteContenedor").click(function()
    {
      $("#content_flotas").load("contenedor/deleteContenedor");
      $("#editContenedor").removeClass("active");
      $("#searchContenedor").removeClass("active");
      $("#addContenedor").removeClass("active");
      $("#deleteContenedor").addClass("active");
      $("#editUnit").removeClass("active");
      $("#addUnit").removeClass("active");
      $("#deleteUnit").removeClass("active");
      $("#searchUnit").removeClass("active");
      $("#editChofer").removeClass("active");
      $("#searchChofer").removeClass("active");
      $("#addChofer").removeClass("active");
      $("#deleteChofer").removeClass("active");
      $("#editChasis").removeClass("active");
      $("#searchChasis").removeClass("active");
      $("#addChasis").removeClass("active");
      $("#deleteChasis").removeClass("active");
      $("#editCabezal").removeClass("active");
      $("#searchCabezal").removeClass("active");
      $("#addCabezal").removeClass("active");
      $("#deleteCabezal").removeClass("active");
   });
$("#searchContenedor").click(function()
    {
      $("#content_flotas").load("contenedor/searchContenedor");
      $("#editContenedor").removeClass("active");
      $("#addContenedor").removeClass("active");
      $("#deleteContenedor").removeClass("active");
      $("#searchContenedor").addClass("active");
      $("#editUnit").removeClass("active");
      $("#addUnit").removeClass("active");
      $("#deleteUnit").removeClass("active");
      $("#searchUnit").removeClass("active");
      $("#editChofer").removeClass("active");
      $("#searchChofer").removeClass("active");
      $("#addChofer").removeClass("active");
      $("#deleteChofer").removeClass("active");
      $("#editChasis").removeClass("active");
      $("#searchChasis").removeClass("active");
      $("#addChasis").removeClass("active");
      $("#deleteChasis").removeClass("active");
      $("#editCabezal").removeClass("active");
      $("#searchCabezal").removeClass("active");
      $("#addCabezal").removeClass("active");
      $("#deleteCabezal").removeClass("active");
   });



$("#addCabezal").click(function()
    {
      $("#content_flotas").load("cabezal/newCabezal");
      $("#editCabezal").removeClass("active");
      $("#searchCabezal").removeClass("active");
      $("#deleteCabezal").removeClass("active");
      $("#addCabezal").addClass("active");
      $("#editUnit").removeClass("active");
      $("#addUnit").removeClass("active");
      $("#deleteUnit").removeClass("active");
      $("#searchUnit").removeClass("active");
      $("#editChofer").removeClass("active");
      $("#searchChofer").removeClass("active");
      $("#addChofer").removeClass("active");
      $("#deleteChofer").removeClass("active");
      $("#editChasis").removeClass("active");
      $("#searchChasis").removeClass("active");
      $("#addChasis").removeClass("active");
      $("#deleteChasis").removeClass("active");
      $("#editContenedor").removeClass("active");
      $("#searchContenedor").removeClass("active");
      $("#addContenedor").removeClass("active");
      $("#deleteContenedor").removeClass("active");
   });
$("#editCabezal").click(function()
    {
      $("#content_flotas").load("cabezal/editCabezal");
      $("#addCabezal").removeClass("active");
      $("#searchCabezal").removeClass("active");
      $("#deleteCabezal").removeClass("active");
      $("#editCabezal").addClass("active");
      $("#editUnit").removeClass("active");
      $("#addUnit").removeClass("active");
      $("#deleteUnit").removeClass("active");
      $("#searchUnit").removeClass("active");
      $("#editChofer").removeClass("active");
      $("#searchChofer").removeClass("active");
      $("#addChofer").removeClass("active");
      $("#deleteChofer").removeClass("active");
      $("#editChasis").removeClass("active");
      $("#searchChasis").removeClass("active");
      $("#addChasis").removeClass("active");
      $("#deleteChasis").removeClass("active");
      $("#editContenedor").removeClass("active");
      $("#searchContenedor").removeClass("active");
      $("#addContenedor").removeClass("active");
      $("#deleteContenedor").removeClass("active");
   });
$("#deleteCabezal").click(function()
    {
      $("#content_flotas").load("cabezal/deleteCabezal");
      $("#editCabezal").removeClass("active");
      $("#searchCabezal").removeClass("active");
      $("#addCabezal").removeClass("active");
      $("#deleteCabezal").addClass("active");
      $("#editUnit").removeClass("active");
      $("#addUnit").removeClass("active");
      $("#deleteUnit").removeClass("active");
      $("#searchUnit").removeClass("active");
      $("#editChofer").removeClass("active");
      $("#searchChofer").removeClass("active");
      $("#addChofer").removeClass("active");
      $("#deleteChofer").removeClass("active");
      $("#editChasis").removeClass("active");
      $("#searchChasis").removeClass("active");
      $("#addChasis").removeClass("active");
      $("#deleteChasis").removeClass("active");
      $("#editContenedor").removeClass("active");
      $("#searchContenedor").removeClass("active");
      $("#addContenedor").removeClass("active");
      $("#deleteContenedor").removeClass("active");
   });
$("#searchCabezal").click(function()
    {
      $("#content_flotas").load("cabezal/searchCabezal");
      $("#editCabezal").removeClass("active");
      $("#addCabezal").removeClass("active");
      $("#deleteCabezal").removeClass("active");
      $("#searchCabezal").addClass("active");
      $("#editUnit").removeClass("active");
      $("#addUnit").removeClass("active");
      $("#deleteUnit").removeClass("active");
      $("#searchUnit").removeClass("active");
      $("#editChofer").removeClass("active");
      $("#searchChofer").removeClass("active");
      $("#addChofer").removeClass("active");
      $("#deleteChofer").removeClass("active");
      $("#editChasis").removeClass("active");
      $("#searchChasis").removeClass("active");
      $("#addChasis").removeClass("active");
      $("#deleteChasis").removeClass("active");
      $("#editContenedor").removeClass("active");
      $("#searchContenedor").removeClass("active");
      $("#addContenedor").removeClass("active");
      $("#deleteContenedor").removeClass("active");
   });

      
