$("#addUnit").click(function()
    {
      $("#content_flotas").load("../unit/newUnit");
      $("#editUnit").removeClass("active");
      $("#searchUnit").removeClass("active");
      $("#deleteUnit").removeClass("active");
      $("#addUnit").addClass("active");
      $("#editWheel").removeClass("active");
      $("#searchWheel").removeClass("active");
      $("#addWheel").removeClass("active");
      $("#deleteWheel").removeClass("active");
      $("#editChofer").removeClass("active");
      $("#searchChofer").removeClass("active");
      $("#addChofer").removeClass("active");
      $("#deleteChofer").removeClass("active");
      $("#editChasis").removeClass("active");
      $("#searchChasis").removeClass("active");
      $("#addChasis").removeClass("active");
      $("#deleteChasis").removeClass("active");
      $("#editContenedor").removeClass("active");
      $("#searchContenedor").removeClass("active");
      $("#addContenedor").removeClass("active");
      $("#deleteContenedor").removeClass("active");
      
   });
$("#editUnit").click(function()
    {
      $("#content_flotas").load("../unit/editUnit");
      $("#addUnit").removeClass("active");
      $("#searchUnit").removeClass("active");
      $("#deleteUnit").removeClass("active");
      $("#editUnit").addClass("active");
      $("#editWheel").removeClass("active");
      $("#searchWheel").removeClass("active");
      $("#addWheel").removeClass("active");
      $("#deleteWheel").removeClass("active");
      $("#editChofer").removeClass("active");
      $("#searchChofer").removeClass("active");
      $("#addChofer").removeClass("active");
      $("#deleteChofer").removeClass("active");
      $("#editChasis").removeClass("active");
      $("#searchChasis").removeClass("active");
      $("#addChasis").removeClass("active");
      $("#deleteChasis").removeClass("active");
      $("#editContenedor").removeClass("active");
      $("#searchContenedor").removeClass("active");
      $("#addContenedor").removeClass("active");
      $("#deleteContenedor").removeClass("active");

   });
$("#deleteUnit").click(function()
    {
      $("#content_flotas").load("../unit/deleteUnit");
      $("#editUnit").removeClass("active");
      $("#searchUnit").removeClass("active");
      $("#addUnit").removeClass("active");
      $("#deleteUnit").addClass("active");
      $("#editWheel").removeClass("active");
      $("#searchWheel").removeClass("active");
      $("#addWheel").removeClass("active");
      $("#deleteWheel").removeClass("active");
      $("#editChofer").removeClass("active");
      $("#searchChofer").removeClass("active");
      $("#addChofer").removeClass("active");
      $("#deleteChofer").removeClass("active");
      $("#editChasis").removeClass("active");
      $("#searchChasis").removeClass("active");
      $("#addChasis").removeClass("active");
      $("#deleteChasis").removeClass("active");
      $("#editContenedor").removeClass("active");
      $("#searchContenedor").removeClass("active");
      $("#addContenedor").removeClass("active");
      $("#deleteContenedor").removeClass("active");

   });
$("#searchUnit").click(function()
    {
      $("#content_flotas").load("../unit/searchUnit");
      $("#editUnit").removeClass("active");
      $("#addUnit").removeClass("active");
      $("#deleteUnit").removeClass("active");
      $("#searchUnit").addClass("active");
      $("#editWheel").removeClass("active");
      $("#searchWheel").removeClass("active");
      $("#addWheel").removeClass("active");
      $("#deleteWheel").removeClass("active");
      $("#editChofer").removeClass("active");
      $("#searchChofer").removeClass("active");
      $("#addChofer").removeClass("active");
      $("#deleteChofer").removeClass("active");
      $("#editChasis").removeClass("active");
      $("#searchChasis").removeClass("active");
      $("#addChasis").removeClass("active");
      $("#deleteChasis").removeClass("active");
      $("#editContenedor").removeClass("active");
      $("#searchContenedor").removeClass("active");
      $("#addContenedor").removeClass("active");
      $("#deleteContenedor").removeClass("active");

   });

$("#addWheel").click(function()
    {
      $("#content_flotas").load("../wheel/newWheel");
      $("#editWheel").removeClass("active");
      $("#searchWheel").removeClass("active");
      $("#deleteWheel").removeClass("active");
      $("#addWheel").addClass("active");
      $("#editUnit").removeClass("active");
      $("#addUnit").removeClass("active");
      $("#deleteUnit").removeClass("active");
      $("#searchUnit").removeClass("active");
      $("#editChofer").removeClass("active");
      $("#searchChofer").removeClass("active");
      $("#addChofer").removeClass("active");
      $("#deleteChofer").removeClass("active");
      $("#editChasis").removeClass("active");
      $("#searchChasis").removeClass("active");
      $("#addChasis").removeClass("active");
      $("#deleteChasis").removeClass("active");
      $("#editContenedor").removeClass("active");
      $("#searchContenedor").removeClass("active");
      $("#addContenedor").removeClass("active");
      $("#deleteContenedor").removeClass("active");
   });
$("#editWheel").click(function()
    {
      $("#content_flotas").load("../wheel/editWheel");
      $("#addWheel").removeClass("active");
      $("#searchWheel").removeClass("active");
      $("#deleteWheel").removeClass("active");
      $("#editWheel").addClass("active");
      $("#editUnit").removeClass("active");
      $("#addUnit").removeClass("active");
      $("#deleteUnit").removeClass("active");
      $("#searchUnit").removeClass("active");
      $("#editChofer").removeClass("active");
      $("#searchChofer").removeClass("active");
      $("#addChofer").removeClass("active");
      $("#deleteChofer").removeClass("active");
      $("#editChasis").removeClass("active");
      $("#searchChasis").removeClass("active");
      $("#addChasis").removeClass("active");
      $("#deleteChasis").removeClass("active");
      $("#editContenedor").removeClass("active");
      $("#searchContenedor").removeClass("active");
      $("#addContenedor").removeClass("active");
      $("#deleteContenedor").removeClass("active");
   });
$("#deleteWheel").click(function()
    {
      $("#content_flotas").load("../wheel/deleteWheel");
      $("#editWheel").removeClass("active");
      $("#searchWheel").removeClass("active");
      $("#addWheel").removeClass("active");
      $("#deleteWheel").addClass("active");
      $("#editUnit").removeClass("active");
      $("#addUnit").removeClass("active");
      $("#deleteUnit").removeClass("active");
      $("#searchUnit").removeClass("active");
      $("#editChofer").removeClass("active");
      $("#searchChofer").removeClass("active");
      $("#addChofer").removeClass("active");
      $("#deleteChofer").removeClass("active");
      $("#editChasis").removeClass("active");
      $("#searchChasis").removeClass("active");
      $("#addChasis").removeClass("active");
      $("#deleteChasis").removeClass("active");
      $("#editContenedor").removeClass("active");
      $("#searchContenedor").removeClass("active");
      $("#addContenedor").removeClass("active");
      $("#deleteContenedor").removeClass("active");
   });
$("#searchWheel").click(function()
    {
      $("#content_flotas").load("../wheel/searchWheel");
      $("#editWheel").removeClass("active");
      $("#addWheel").removeClass("active");
      $("#deleteWheel").removeClass("active");
      $("#searchWheel").addClass("active");
      $("#editUnit").removeClass("active");
      $("#addUnit").removeClass("active");
      $("#deleteUnit").removeClass("active");
      $("#searchUnit").removeClass("active");
      $("#editChofer").removeClass("active");
      $("#searchChofer").removeClass("active");
      $("#addChofer").removeClass("active");
      $("#deleteChofer").removeClass("active");
      $("#editChasis").removeClass("active");
      $("#searchChasis").removeClass("active");
      $("#addChasis").removeClass("active");
      $("#deleteChasis").removeClass("active");
      $("#editContenedor").removeClass("active");
      $("#searchContenedor").removeClass("active");
      $("#addContenedor").removeClass("active");
      $("#deleteContenedor").removeClass("active");
   });


$("#addChofer").click(function()
    {
      $("#content_flotas").load("../chofer/newChofer");
      $("#editChofer").removeClass("active");
      $("#searchChofer").removeClass("active");
      $("#deleteChofer").removeClass("active");
      $("#addChofer").addClass("active");
      $("#editUnit").removeClass("active");
      $("#addUnit").removeClass("active");
      $("#deleteUnit").removeClass("active");
      $("#searchUnit").removeClass("active");
      $("#editWheel").removeClass("active");
      $("#searchWheel").removeClass("active");
      $("#addWheel").removeClass("active");
      $("#deleteWheel").removeClass("active");
      $("#editChasis").removeClass("active");
      $("#searchChasis").removeClass("active");
      $("#addChasis").removeClass("active");
      $("#deleteChasis").removeClass("active");
      $("#editContenedor").removeClass("active");
      $("#searchContenedor").removeClass("active");
      $("#addContenedor").removeClass("active");
      $("#deleteContenedor").removeClass("active");
   });
$("#editChofer").click(function()
    {
      $("#content_flotas").load("../chofer/editChofer");
      $("#addChofer").removeClass("active");
      $("#searchChofer").removeClass("active");
      $("#deleteChofer").removeClass("active");
      $("#editChofer").addClass("active");
      $("#editUnit").removeClass("active");
      $("#addUnit").removeClass("active");
      $("#deleteUnit").removeClass("active");
      $("#searchUnit").removeClass("active");
      $("#editWheel").removeClass("active");
      $("#searchWheel").removeClass("active");
      $("#addWheel").removeClass("active");
      $("#deleteWheel").removeClass("active");
      $("#editChasis").removeClass("active");
      $("#searchChasis").removeClass("active");
      $("#addChasis").removeClass("active");
      $("#deleteChasis").removeClass("active");
      $("#editContenedor").removeClass("active");
      $("#searchContenedor").removeClass("active");
      $("#addContenedor").removeClass("active");
      $("#deleteContenedor").removeClass("active");
   });
$("#deleteChofer").click(function()
    {
      $("#content_flotas").load("../chofer/deleteChofer");
      $("#editChofer").removeClass("active");
      $("#searchChofer").removeClass("active");
      $("#addChofer").removeClass("active");
      $("#deleteChofer").addClass("active");
      $("#editUnit").removeClass("active");
      $("#addUnit").removeClass("active");
      $("#deleteUnit").removeClass("active");
      $("#searchUnit").removeClass("active");
      $("#editWheel").removeClass("active");
      $("#searchWheel").removeClass("active");
      $("#addWheel").removeClass("active");
      $("#deleteWheel").removeClass("active");
      $("#editChasis").removeClass("active");
      $("#searchChasis").removeClass("active");
      $("#addChasis").removeClass("active");
      $("#deleteChasis").removeClass("active");
      $("#editContenedor").removeClass("active");
      $("#searchContenedor").removeClass("active");
      $("#addContenedor").removeClass("active");
      $("#deleteContenedor").removeClass("active");
   });
$("#searchChofer").click(function()
    {
      $("#content_flotas").load("../chofer/searchChofer");
      $("#editChofer").removeClass("active");
      $("#addChofer").removeClass("active");
      $("#deleteChofer").removeClass("active");
      $("#searchChofer").addClass("active");
      $("#editUnit").removeClass("active");
      $("#addUnit").removeClass("active");
      $("#deleteUnit").removeClass("active");
      $("#searchUnit").removeClass("active");
      $("#editWheel").removeClass("active");
      $("#searchWheel").removeClass("active");
      $("#addWheel").removeClass("active");
      $("#deleteWheel").removeClass("active");
      $("#editChasis").removeClass("active");
      $("#searchChasis").removeClass("active");
      $("#addChasis").removeClass("active");
      $("#deleteChasis").removeClass("active");
      $("#editContenedor").removeClass("active");
      $("#searchContenedor").removeClass("active");
      $("#addContenedor").removeClass("active");
      $("#deleteContenedor").removeClass("active");
   });


$("#addChasis").click(function()
    {
      $("#content_flotas").load("../chasis/newChasis");
      $("#editChasis").removeClass("active");
      $("#searchChasis").removeClass("active");
      $("#deleteChasis").removeClass("active");
      $("#addChasis").addClass("active");
      $("#editUnit").removeClass("active");
      $("#addUnit").removeClass("active");
      $("#deleteUnit").removeClass("active");
      $("#searchUnit").removeClass("active");
      $("#editWheel").removeClass("active");
      $("#searchWheel").removeClass("active");
      $("#addWheel").removeClass("active");
      $("#deleteWheel").removeClass("active");
      $("#editChofer").removeClass("active");
      $("#searchChofer").removeClass("active");
      $("#addChofer").removeClass("active");
      $("#deleteChofer").removeClass("active");
      $("#editContenedor").removeClass("active");
      $("#searchContenedor").removeClass("active");
      $("#addContenedor").removeClass("active");
      $("#deleteContenedor").removeClass("active");
   });
$("#editChasis").click(function()
    {
      $("#content_flotas").load("../chasis/editChasis");
      $("#addChasis").removeClass("active");
      $("#searchChasis").removeClass("active");
      $("#deleteChasis").removeClass("active");
      $("#editChasis").addClass("active");
      $("#editUnit").removeClass("active");
      $("#addUnit").removeClass("active");
      $("#deleteUnit").removeClass("active");
      $("#searchUnit").removeClass("active");
      $("#editWheel").removeClass("active");
      $("#searchWheel").removeClass("active");
      $("#addWheel").removeClass("active");
      $("#deleteWheel").removeClass("active");
      $("#editChofer").removeClass("active");
      $("#searchChofer").removeClass("active");
      $("#addChofer").removeClass("active");
      $("#deleteChofer").removeClass("active");
      $("#editContenedor").removeClass("active");
      $("#searchContenedor").removeClass("active");
      $("#addContenedor").removeClass("active");
      $("#deleteContenedor").removeClass("active");
   });
$("#deleteChasis").click(function()
    {
      $("#content_flotas").load("../chasis/deleteChasis");
      $("#editChasis").removeClass("active");
      $("#searchChasis").removeClass("active");
      $("#addChasis").removeClass("active");
      $("#deleteChasis").addClass("active");
      $("#editUnit").removeClass("active");
      $("#addUnit").removeClass("active");
      $("#deleteUnit").removeClass("active");
      $("#searchUnit").removeClass("active");
      $("#editWheel").removeClass("active");
      $("#searchWheel").removeClass("active");
      $("#addWheel").removeClass("active");
      $("#deleteWheel").removeClass("active");
      $("#editChofer").removeClass("active");
      $("#searchChofer").removeClass("active");
      $("#addChofer").removeClass("active");
      $("#deleteChofer").removeClass("active");
      $("#editContenedor").removeClass("active");
      $("#searchContenedor").removeClass("active");
      $("#addContenedor").removeClass("active");
      $("#deleteContenedor").removeClass("active");
   });
$("#searchChasis").click(function()
    {
      $("#content_flotas").load("../chasis/searchChasis");
      $("#editChasis").removeClass("active");
      $("#addChasis").removeClass("active");
      $("#deleteChasis").removeClass("active");
      $("#searchChasis").addClass("active");
      $("#editUnit").removeClass("active");
      $("#addUnit").removeClass("active");
      $("#deleteUnit").removeClass("active");
      $("#searchUnit").removeClass("active");
      $("#editWheel").removeClass("active");
      $("#searchWheel").removeClass("active");
      $("#addWheel").removeClass("active");
      $("#deleteWheel").removeClass("active");
      $("#editChofer").removeClass("active");
      $("#searchChofer").removeClass("active");
      $("#addChofer").removeClass("active");
      $("#deleteChofer").removeClass("active");
      $("#editContenedor").removeClass("active");
      $("#searchContenedor").removeClass("active");
      $("#addContenedor").removeClass("active");
      $("#deleteContenedor").removeClass("active");
   });


$("#addContenedor").click(function()
    {
      $("#content_flotas").load("../contenedor/newContenedor");
      $("#editContenedor").removeClass("active");
      $("#searchContenedor").removeClass("active");
      $("#deleteContenedor").removeClass("active");
      $("#addContenedor").addClass("active");
      $("#editUnit").removeClass("active");
      $("#addUnit").removeClass("active");
      $("#deleteUnit").removeClass("active");
      $("#searchUnit").removeClass("active");
      $("#editWheel").removeClass("active");
      $("#searchWheel").removeClass("active");
      $("#addWheel").removeClass("active");
      $("#deleteWheel").removeClass("active");
      $("#editChofer").removeClass("active");
      $("#searchChofer").removeClass("active");
      $("#addChofer").removeClass("active");
      $("#deleteChofer").removeClass("active");
      $("#editChasis").removeClass("active");
      $("#searchChasis").removeClass("active");
      $("#addChasis").removeClass("active");
      $("#deleteChasis").removeClass("active");

   });
$("#editContenedor").click(function()
    {
      $("#content_flotas").load("../contenedor/editContenedor");
      $("#addContenedor").removeClass("active");
      $("#searchContenedor").removeClass("active");
      $("#deleteContenedor").removeClass("active");
      $("#editContenedor").addClass("active");
      $("#editUnit").removeClass("active");
      $("#addUnit").removeClass("active");
      $("#deleteUnit").removeClass("active");
      $("#searchUnit").removeClass("active");
      $("#editWheel").removeClass("active");
      $("#searchWheel").removeClass("active");
      $("#addWheel").removeClass("active");
      $("#deleteWheel").removeClass("active");
      $("#editChofer").removeClass("active");
      $("#searchChofer").removeClass("active");
      $("#addChofer").removeClass("active");
      $("#deleteChofer").removeClass("active");
      $("#editChasis").removeClass("active");
      $("#searchChasis").removeClass("active");
      $("#addChasis").removeClass("active");
      $("#deleteChasis").removeClass("active");
   });
$("#deleteContenedor").click(function()
    {
      $("#content_flotas").load("../contenedor/deleteContenedor");
      $("#editContenedor").removeClass("active");
      $("#searchContenedor").removeClass("active");
      $("#addContenedor").removeClass("active");
      $("#deleteContenedor").addClass("active");
      $("#editUnit").removeClass("active");
      $("#addUnit").removeClass("active");
      $("#deleteUnit").removeClass("active");
      $("#searchUnit").removeClass("active");
      $("#editWheel").removeClass("active");
      $("#searchWheel").removeClass("active");
      $("#addWheel").removeClass("active");
      $("#deleteWheel").removeClass("active");
      $("#editChofer").removeClass("active");
      $("#searchChofer").removeClass("active");
      $("#addChofer").removeClass("active");
      $("#deleteChofer").removeClass("active");
      $("#editChasis").removeClass("active");
      $("#searchChasis").removeClass("active");
      $("#addChasis").removeClass("active");
      $("#deleteChasis").removeClass("active");
   });
$("#searchContenedor").click(function()
    {
      $("#content_flotas").load("../contenedor/searchContenedor");
      $("#editContenedor").removeClass("active");
      $("#addContenedor").removeClass("active");
      $("#deleteContenedor").removeClass("active");
      $("#searchContenedor").addClass("active");
      $("#editUnit").removeClass("active");
      $("#addUnit").removeClass("active");
      $("#deleteUnit").removeClass("active");
      $("#searchUnit").removeClass("active");
      $("#editWheel").removeClass("active");
      $("#searchWheel").removeClass("active");
      $("#addWheel").removeClass("active");
      $("#deleteWheel").removeClass("active");
      $("#editChofer").removeClass("active");
      $("#searchChofer").removeClass("active");
      $("#addChofer").removeClass("active");
      $("#deleteChofer").removeClass("active");
      $("#editChasis").removeClass("active");
      $("#searchChasis").removeClass("active");
      $("#addChasis").removeClass("active");
      $("#deleteChasis").removeClass("active");
   });

